# Generated by Django 4.1.2 on 2022-11-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mvt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=50)),
                ('dia', models.CharField(max_length=50)),
                ('horario', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='clase_comida',
        ),
    ]
